export const DATE_TYPES = {
  OETA: 'OETA',
  LETA: 'LETA',
  AETA: 'AETA',
};

export const UPDATE_TYPES = {
  ETB: 6,
  ETD: 7,
  LETB: 8,
  LETD: 9,
  BOARDING: 10,
  PTW: 11,
  ALL: 100,
};

export const initialPlanningState = {
  Id: 0,
  PlaningNo: '',
  PlaningDate: new Date(),
  FromDate: new Date(),
  ToDate: new Date(),
  Remarks: '',
  SearchText: '',
  PortFilter: '',
  DateType: DATE_TYPES.AETA,
  Details: [],
};

export const initialDetailRow = {
  Id: 0,
  SortBy: 0,
  SaleOrderMasterRefId: 0,
  JobNo: '',
  JobDate: null,
  CustomerName: '',
  Origin: '',
  Destination: '',
  Vessel: '',
  ETA: null,
  ETB: null,
  ETD: null,
  OETA: null,
  OETB: null,
  OETD: null,
  JobStatus: '',
  Commodity: '',
  pkg: '',
  Cargo: '',
  PTW: '',
  BoardingOfficerRefid: null,
  BoardingOfficerName: '',
  BoardingOfficer1Refid: null,
  BoardingOfficerName1: '',
  BoardingAmount: 0,
  BoardingAmount1: 0,
  AgentName: '',
  AgentPhone: '',
  Remarks: '',
};
