export const initialRTIState = {
  // Form fields
  rtiNo: '',
  rtiDate: new Date(),
  driverRefId: '',
  truckRefId: '',
  agentCompanyRefId: '',
  agentRefId: '',
  eLink: '1ST LINK',
  exLink: '2ND LINK',
  sleeping: 'NO',
  exitYN: 'NO',
  emptyDeliveryYN: 'NO',
  pickup: 'NO',
  addDrop: 'NO',
  manpw: 'NO',
  pickupCount: '',
  dropCount: '',
  destination: '',
  sealBy: '',
  breakSealBy: '',
  remarks: '',
  comments: '',
  punctuality: false,
  documentSub: false,
  pckHandling: false,
  
  // Calculations
  totalAmount: 0,
  sleepingamount: 0,
  exitamount: 0,
  EmptyDeliveryamount: 0,
  pickupamount: 0,
  dropamount: 0,
  manpoweramount: 0,
  
  // Grid data
  gridData: [],
  
  // Meta
  editId: 0,
  editStatus: 0,
};

export const initialGridRow = {
  JobNo: '',
  CustomerName: '',
  JobDate: '',
  Salary: 0,
  PPIC: '',
  DPIC: '',
  PWDType: 0,
  OriginD: '',
  DestinationD: '',
  PickupDateD: '',
  DeliveryDateD: '',
  PickupAddressD: '',
  DeliveryAddressD: '',
  PickupAddressTimelistD: '',
  PickupAddressQuantityD: '',
  DeliveryAddressQuantityD: '',
  DeliveryAddressdatelistD: '',
  Sleeping: false,
  OnTime: false,
  TruckMaintenance: false,
  DoSubmission: false,
  Id: 0,
  SaleOrderMasterRefId: 0,
  RTIMasterRefId: 0,
  EditMode: 0,
};
